### ISSUE TITLE
big.Rat equivalence?

### ISSUE THREAD

**Issue by tsenart** [shopspring/decimal#1]
Hey there!

I saw this library featured in http://golangweekly.com/issues/49 and the first thing that occurred to me was why wouldn't you use the stdlib `math/big` library. Would you please elucidate me on this one?
Here's the equivalent README example using `math/big`.

```go
package main

import (
	"fmt"
	"math/big"
)

func main() {
	price, ok := new(big.Rat).SetString("136.02")
	if !ok {
		panic("parsing decimal failed")
	}

	quantity := new(big.Rat).SetFloat64(3)

	fee, _ := new(big.Rat).SetString(".035")
	taxRate, _ := new(big.Rat).SetString(".08875")

	subtotal := new(big.Rat).Mul(price, quantity)

	preTax := new(big.Rat).Mul(subtotal, new(big.Rat).Add(fee, new(big.Rat).SetFloat64(1)))

	total := new(big.Rat).Mul(preTax, new(big.Rat).Add(taxRate, new(big.Rat).SetFloat64(1)))

	fmt.Println("Subtotal:", subtotal.FloatString(9))
	fmt.Println("Pre-tax:", preTax.FloatString(9))
	fmt.Println("Taxes:", new(big.Rat).Sub(total, preTax).FloatString(9))
	fmt.Println("Total:", total.FloatString(9))
	fmt.Println("Tax rate:", new(big.Rat).Quo(new(big.Rat).Sub(total, preTax), preTax).FloatString(9))
}
```

Which outputs:
```
Subtotal: 408.060000000
Pre-tax: 422.342100000
Taxes: 37.482861375
Total: 459.824961375
Tax rate: 0.088750000
```

**Comment by vadimg** [comment]
This is the most frequently asked question about this library (I should probably create an FAQ, just for this question).

Using fixed-point decimals is preferable to using big.Rat for representing money. Here's a contrived example:

Let's say you use big.Rat, and you have two numbers, x and y, both representing 1/3, and you have z = 1 - x - y = 1/3. If you print each one out, the string output has to stop somewhere (let's say it stops at 3 decimal digits, for simplicity), so you'll get 0.333, 0.333, and 0.333. But where did the other 0.001 go?

If you use a fixed-point decimal, the strings being printed out represent the number exactly. So, if you have x = y = 1/3 (with precision 3), they will actually be equal to 0.333, and when you do z = 1 - x - y, z will be equal to .334. No money is unaccounted for!

Check this out: http://play.golang.org/p/lCZZs0w9KE to see what I mean. Of course, this is a contrived example, and with careful coding, it's possible to avoid losing 0.001. But in a large financial application with many calculations, built by many developers, it's easy to make this kind of mistake and lose track of money.

**Comment by tsenart** [comment]
That makes sense. Thanks for the explanation. And +1 for a FAQ. :)
