### ISSUE TITLE
newFromInt?

### ISSUE THREAD

**Issue by kempeng** [shopspring/decimal#104]
Hi,

I am enjoying using the decimal package, but sometimes I find myself wanting to do a simple math operation between a decimal and an int. To provide some lower level support for those type of operations, would it be helpful to create a function like NewFromInt() (and perhaps int32 and int64 variants), do be able to do "inline" conversions of ints to decimals in math operations, e.g.
var a Deicmal
a.Div(NewFromInt(IntVar))

Any thoughts?

**Comment by peterstace** [comment]
You could just use `a.Div(decimal.New(IntVar, 0))`.

Having `NewFromInt`, `NewFromInt64`, `NewFromInt32` etc would be nice helpers though, and save a bunch of type casting.

**Comment by kempeng** [comment]
agree, fixed in new update
