### ISSUE TITLE
Sqrt() ?

### ISSUE THREAD

**Issue by kempeng** [shopspring/decimal#105]
Hi,

I want to compute the square root of a decimal, and realized that this function is not implemented, and it is probably difficult to implement it for the decimal number representation from the ground up? 

Alternatively, I could accept converting a decimal value to a float or bigFloat and use the available Sqrt() functions.

However, the decimal package has no functions to export a decimal to another representation (other than string).

Any suggestions how to implement a conversion of decimal to, for example, float64 or Float?

**Comment by peterstace** [comment]
There's already a [conversion to float64](https://godoc.org/github.com/shopspring/decimal#Decimal.Float64).

**Comment by kempeng** [comment]
A straightforward implementation of Sqrt in decimal:

package decimal

// Sqrt returns the square root of d, the result will have
// DivisionPrecision digits after the decimal point.
func Sqrt(d Decimal) Decimal {
	s, _ := SqrtRound(d, int32(DivisionPrecision))
	return s
}

// SqrtRound returns the square root of d, the result will have
// precision digits after the decimal point. The bool precise returns whether the precision was reached
func SqrtRound(n Decimal, precision int32) (Decimal, bool) {
	cutoff := decimal.New(1, -precision)
	lo := Zero
	hi := n
	var mid Decimal
	for i := 0; i < 100000; i++ {
		//mid = (lo+hi)/2;
		mid = lo.Add(hi).DivRound(New(2, 0), precision)
		if mid.Mul(mid).Sub(n).Abs().LessThan(cutoff) {
			return mid, true
		}
		if mid.Mul(mid).GreaterThan(n) {
			hi = mid
		} else {
			lo = mid
		}
	}
	return mid, false
}

**Comment by kempeng** [comment]
submitted code as a PR
