### ISSUE TITLE
NewFromInt, NewFromInt32 and other convenience constructors

### ISSUE THREAD

**Issue by pascallouisperez** [shopspring/decimal#11]
Have you considered having simpler constructors

```
NewFromInt(v) = New(int64(v), 0)
```

etc.?

**Comment by chakrit** [comment]
Or just `decimal.FromInt()` or `decimal.FromFloat()` would've suffice.

**Comment by vadimg** [comment]
I have nothing against having more NewFromX constructors, and I welcome pull requests!
