### ISSUE TITLE
Pointer Receivers

### ISSUE THREAD

**Issue by sdcoffey** [shopspring/decimal#13]
Is there a reason that this package mostly deals in value types? It makes json-ifying things somewhat tricky in some cases. Consider the following:

```golang
type WireType struct {
	Id  int             `"json:id"`
	Num decimal.Decimal `json:"num,string,omitempty"`
}
```

When this struct is marshaled, it will never omit `Num`, because `json` doesn't know when `Num` is zero.

The obvious fix for this is to make `Num` a pointer type, but since this lib relies heavliy on non-mutable/value types, this turns otherwise nice-looking code:

```golang
params := WireType{1, decimal.NewFromFloat(1.0),}
factor := decimal.NewFromFloat(2.0).Mul(params.Num)
```

Into this (where num is of type `*decimal.Decimal`):

```golang
one := decimal.NewFromFloat(1.0)
params := WireType{1, &one,}
factor := one.Mul(*params.Num)
```

Small potatoes? Maybe. But it would clean up the code a bit and make the API nicer in situations like this, especially in libraries which depend on `decimal`, which then results in the end developer needing to always dereference `Decimal` types in structs which depend on them.

 Happy to work on a PR for this unless there are any fundamental objections.

**Comment by EricLagergren** [comment]
FWIW (I've never contributed to this library) changing from non-pointer to pointer receivers is an API-breaking change that could have devastating impacts on code that uses decimal types (e.g., monetary calculations.

**Comment by vadimg** [comment]
Yeah, I prefer not to break the API, given that many people have already written code around the current API, and the benefit is not huge (and there are probably drawbacks I am not thinking of).
