### ISSUE TITLE
Tagging Releases Align with Go Modules

### ISSUE THREAD

**Issue by horacehylee** [shopspring/decimal#132]
Hey all! Thanks for the really useful package.

Since Go 1.11 came out with go modules, could we add extra tags like `v1.1.0` in the repo, such that we are reference that particular version of this package using `go mod`? 

In order to be compatible with others using `go dep`, we could just create new tags `v1.1.0` from the commit with `1.1.0` tag.

Reference:
https://github.com/golang/go/wiki/Modules#semantic-import-versioning

**Comment by dvic** [comment]
any updates on this?

**Comment by mwoss** [comment]
@horacehylee @dvic Support for go modules will be available from next release

**Comment by pepsighan** [comment]
go.dev shows this package at v0.0.0. It would be awesome if there was a proper version as per go modules. Things can go wrong between updates of breaking changes.

**Comment by mwoss** [comment]
Yes, we are aware of that. We will probably release 1.2.0 version this week or at the beginning of the next week - we have to fix a few more issues. So with that release, we will tag all previous changes (1.0.0, 1.0.1 and 1.1.0).

**Comment by mwoss** [comment]
Hi all. We will probably postpone 1.2.0 release until the end of this week. We are trying to implement an improved `Pow` method (tracked in #55). We time-boxed this task, so if we don't make it in time, we will release 1.2.0 without this fix/feature and we will work on it in the next release schedule. Thanks for your patience.

**Comment by mwoss** [comment]
Closing, resolved along with releasing v1.2.0 :DD
