### ISSUE TITLE
The comments for func StringFixedBank is not correctly

### ISSUE THREAD

**Issue by 10gic** [shopspring/decimal#133]
The comments for func StringFixedBank is copied from func StringFixed, See https://github.com/shopspring/decimal/blob/cd690d0c9e2447b1ef2a129a6b7b49077da89b8e/decimal.go#L731

**Comment by mwoss** [comment]
@10gic Thanks for pointing this :) We will fix it in as soon as possible,

**Comment by mwoss** [comment]
Fixed, closing :D
