### ISSUE TITLE
Is somebody still actively maintaining and updating the master?

### ISSUE THREAD

**Issue by kempeng** [shopspring/decimal#135]
I see a lot of issue solutions and pull requests not be updated into the master? Is the master still actively maintained?

**Comment by tangphillip** [comment]
https://techcrunch.com/2018/10/25/can-shoprunner-compete-with-amazon-sam-yagan-wants-to-find-out/

I suspect that the new owners aren't maintaining `decimal`. If the community is still using this, I think the best bet is for someone to fork it and maintain the fork.

**Comment by mwoss** [comment]
@kempeng @tangphillip 
Yes, decimal lib is still maintained by me (new member) and @njason. At the moment we are working on 1.2.0 release.
