### ISSUE TITLE
[Question] How do I truncate a decimal to 2 decimal places?

### ISSUE THREAD

**Issue by elfgoh** [shopspring/decimal#146]
What is the approach when trying to truncate a decimal to 2 decimal places? 

The closest I can find are 

- https://godoc.org/github.com/shopspring/decimal#Decimal.StringFixed
- https://godoc.org/github.com/shopspring/decimal#Decimal.Truncate

But they dont meet my specific requirements.

Example. 

- 123 becomes 123.00
- 123.456 becomes 123.45

**Comment by leighmcculloch** [comment]
Those two functions will do what you requested in your example, you just need to use them together.

Example:
```go
d := decimal.New(123, 0)
fmt.Println(d)
fmt.Println(d.Truncate(2).StringFixed(2))
// Output: 
// 123
// 123.00
```
```go
d := decimal.New(123456, -3)
fmt.Println(d)
fmt.Println(d.Truncate(2).StringFixed(2))
// Output: 
// 123.456
// 123.45
```
https://play.golang.org/p/T8eUnXm1G1g

**Comment by mwoss** [comment]
Thanks again for your explanation @leighmcculloch  : )
I hope everything is clear now @elfgoh
