### ISSUE TITLE
loss of precision for large number of floating number adding

### ISSUE THREAD

**Issue by zjn1234** [shopspring/decimal#148]
there are many float64 number to be added,i use this

`totalServiceFee := decimal.NewFromFloat(0.0)

for {
     totalServiceFee = totalServiceFee.Add(decimal.NewFromFloat(x))
}`

but the result has loss of precision

it can't solve problem like this ???

**Comment by mwoss** [comment]
@zjn1234 Our decimal library can "only" represent numbers with a maximum of 2^31 digits after the decimal point. Maybe this was an issue you faced back then.

**Comment by zjn1234** [comment]
@mwoss thanks

**Comment by mwoss** [comment]
@zjn1234 btw You could try `NewFromFloatWithExponent` where you can specify the precision in absolute terms.
