### ISSUE TITLE
Negative exponent values produce incorrect float values

### ISSUE THREAD

**Issue by kstenerud** [shopspring/decimal#151]
```golang
func TestNegativeExponent(t *testing.T) {
	v := decimal.NewFromFloatWithExponent(15, -1)
	expected := 1.5
	actual, _ := v.Float64()
	if expected != actual {
		t.Errorf("Expected %v but got %v", expected, actual)
	}
}
```
```
--- FAIL: TestNegativeExponent (0.00s)
    compact-float_test.go:76: Expected 1.5 but got 15
FAIL
```

**Comment by StanleyDing** [comment]
I think the second argument `exp` is used for precision. From the doc:
> NewFromFloatWithExponent(123.456, -2).String() // output: "123.46"

**Comment by leighmcculloch** [comment]
What you might want is simply the `New` function which accepts an int value and an int exponent which can then be extracted as a float.

Example:
```go
v := decimal.New(15, -1)
actual, _ := v.Float64() // will be 1.5
```
https://play.golang.org/p/HqIQVGyPAmQ

**Comment by mwoss** [comment]
@kstenerud I think the above posts explained everything. Anyways, I'm aware the naming can be a little confusing, but changing it may break backward compatibility. 

@StanleyDing @leighmcculloch thanks for your explanations :)
