### ISSUE TITLE
Calculate 10% (Example) of decimal value

### ISSUE THREAD

**Issue by bcashier** [shopspring/decimal#154]
Hi,

Is there a solution to calculate 10% of some value without using NewFromString etc ...

Here is my example:
```
hundred, _ := decimal.NewFromString("100")
ten, _ := decimal.NewFromString("10")
toInvest = toInvest.Mul(ten).DivRound(hundred, 2)
```

Is there a way without converting 100 and 10 to decimal or quicker solution than this ?

Thanks

**Comment by leighmcculloch** [comment]
You can create decimals without calling `NewFromString`. If you know the number and you can express it in the form `value * 10 ^ exp`, then you can use `New(value int64, exp int32)` which as a bonus doesn't return an error.

Example with one-hundred:
```
100 * 10 ^ 0 = 100
```
```go
hundred := decimal.New(100, 0)
```

Example:
https://play.golang.org/p/OGdNtpPOrT6

**Comment by bcashier** [comment]
@leighmcculloch I didn't knew about it !

Thank you very much for your answer, really appreciate it !
