### ISSUE TITLE
Need two API: get precision from decimal, get how many digits from decimal

### ISSUE THREAD

**Issue by guotie** [shopspring/decimal#164]
1. get precision from decimal

how many digital number after dot

2. get how many digits from decimal

how many digital numbers, for example, 1.632, there are 4 numbers

**Comment by mwoss** [comment]
Ad. 1 You can use decimal's `exp` attribute
Ad. 2 There is no, go-to solution, atm the simplest solution would be casting decimal's `value` attribute to string and then checking the length of that string. `len(d.value.String())`

**Comment by guotie** [comment]
what does `exp` attribute means

**Comment by mwoss** [comment]
Decimal struct contains two fields: `value` and `exp`.
```
type Decimal struct {
	value *big.Int
	exp int32
}
```
Let's take `1.123` as a decimal example.
`value` stores number without a decimal point in this example `1123`
`exp` stores information about decimal point, `-3` for given decimal. Basically `exp` stands for the exponent, which means the number of tens you multiply a `value` by. In scientific notation (using exponent) above number could be written as 1123e-3.

**Comment by guotie** [comment]
but exp is private

**Comment by mwoss** [comment]
Oh, sorry. I've focused on explaining the meaning of the Decimal struct field, forgetting to mention two getters you can use: `Exponent` and `Value`.

**Comment by guotie** [comment]
why not just privide a method like Precision() to return the decimal's precision?

**Comment by mwoss** [comment]
I don't see much value in such a method, as you have access to decimal's value and exp attribute by `Value` and `Exponent`, but I will consider that for sure as I believe it could be also helpful for some people.

**Comment by guotie** [comment]
Exponent return negative, and the function name is ambiguous

**Comment by mwoss** [comment]
Agree, that's a valid point. I will add this to our backlog. Thanks, for the idea.
