### ISSUE TITLE
Using not the specified exponent for NewFromFloatWithExponent

### ISSUE THREAD

**Issue by ValentinMezev** [shopspring/decimal#177]
`decimal.NewFromFloatWithExponent(x, -5)`
For x = 1.24 it gives me 124 with exponent -5
For x = 1.26 it gives me 126 with exponent -5
For x = 1.25 however it gives me 125 with exponent -2

later I want to use res.Coefficient().Int64() and receive 124000 but for 1.25 I could not get 125000.

**Comment by mwoss** [comment]
Hi @ValentinMezev. You may be surprised, but this is a correct behavior of the `decimal` library. Floats are a bit of tricky data types. 
Let me explain it. Not all floating-point numbers can be exactly represented by computers as they live in the binary system world (1|0). Those two numbers you mentioned above could be a good example: 1.24 and 1.26. They are represented respectively inside computers as: `1.2399999999999999911182158029987476766109466552734375` and `1.2600000000000000088817841970012523233890533447265625`. So when you initialize new decimal using `NewFromFloatWithExponent` we take that exact float representation and then we use it for further processing. Try and initialize decimal using this code: `NewFromFloatWithExponent(x, -18)` you will notice a difference.
On the other hand, 1.25 can be exactly represented inside current computers. It's 1.25 a no more number after the decimal point.  When you initialized it using `exp = -5 ` we check whether we can initialize decimal with such exp parameter or not and if we cannot. we use max possible exp value for given float. 
I know decimal initialization using float can be confusing. I will try to enhance documentation, so it can be clear for everyone. :D

**Comment by ValentinMezev** [comment]
Thanks for the clarifications.
I hope it will be useful for other people as well.
I also think it will be valuable to have more info about this in the documentation.
