### ISSUE TITLE
Wrong calculate Pow

### ISSUE THREAD

**Issue by vxxvvxxv** [shopspring/decimal#178]
I wanted to use your library, but noticed that the function pow does not think correctly. Here is a comparison with math.Pow

```go
fmt.Println(decimal.NewFromFloat(1.15).Pow(decimal.NewFromFloat(12.1666667)))
// result: 5.350250105473711181640625
```

```go
fmt.Println(math.Pow(1.15,12.1666667))
// result: 5.476339866422567
```

**Comment by mwoss** [comment]
Hi @XeHeSi. Yes, we are aware of that, the issue is tracked in #55. Right now it's our main priority to implement is correctly.
