### ISSUE TITLE
How to convert decimal to int for money calculation purpose?

### ISSUE THREAD

**Issue by bgruszka** [shopspring/decimal#190]
Hello,

I use decimal lib for money purpose and is it possible to get value as cents.

For example:

I have 1.23 eur and I would like to have it in cents (123). How to convert it?

**Comment by mwoss** [comment]
Hi @bgruszka! 
Basically, it would depend on what result type you are expecting. I will give you a few examples right now and we can find an ideal solution later on when you will respond.

```go
d := decimal.RequireFromString("1.23")

// 1. decimal.Coefficient
fmt.Println(d.Coefficient()) // It would return *big.Int, it works only if exp = -2 as we rely on 10^exp scaling here

// 2. Multiplying - decmal.Mul
hundred:= decimal.New(100, 0)
fmt.Println(d.Mul(hundred)) // returns new decimal

// 3. Mutypling + cast to string
fmt.Println(d.Mul(hundred).String()) // returns string
```
I would say the safest option is to just multiply the given decimal by 100. What is your exact use-case?

**Comment by mwoss** [comment]
Closing, due to lack of activity. If you have any other question @bgruszka please reopen the issue or create the new one :)
