### ISSUE TITLE
Add support for UnmarshalText and MarshalText for NullDecimal

### ISSUE THREAD

**Issue by bharath23** [shopspring/decimal#193]
Like support for JSON it would be nice to have support for XML for NullDecimal.

I have submitted PR #192 which add support for it.

**Comment by mwoss** [comment]
Thanks for submitting the pull reqeuest! I will try to look at it tomorrow.

**Comment by mwoss** [comment]
Closing, waiting for the PR author response.

**Comment by bharath23** [comment]
Updated PR based on you comments.
