### ISSUE TITLE
what is the best way to implement the operator +=

### ISSUE THREAD

**Issue by hmuschett** [shopspring/decimal#195]
what is the best way to implement the += operator  between two Decimal

**Comment by mwoss** [comment]
Golang does not support operator overloading. So there is no way to explicitly implement += operation od decimals using this library,
To sum two decimal you can use the `Add` method instead.
For example:
```go
d1 := decimal.RequireFromString("1.5")
d2 := decimal.RequireFromString("1.6")

d1.Add(d2)
```
