### ISSUE TITLE
How to store the numbers in mongodb

### ISSUE THREAD

**Issue by waghcwb** [shopspring/decimal#217]
This library does not support [`decimal128`](https://docs.mongodb.com/manual/tutorial/model-monetary-data/#numeric-decimal) introduced by mongodb, so what is the best format to save an number in db?

**Comment by felipeneuwald** [comment]
I am converting the value to type float64 and then storing it.

```go
// DecimalToFloat64 receives a d decimal.Decimal and returns a float64
func DecimalToFloat64(d decimal.Decimal) float64 {
	f, _ := d.Float64()
	return f
}
```

**Comment by waghcwb** [comment]
@felipeneuwald,
thank you, that worked.
