### ISSUE TITLE
The correct way of using decimal

### ISSUE THREAD

**Issue by rif** [shopspring/decimal#22]
What would be the correct way to handle this operations to get exactly the initial 0.19 back?

```go
package main

import (
	"fmt"

	"github.com/shopspring/decimal"
)

func main() {
	p := decimal.NewFromFloat(0.19)
	sixty := decimal.NewFromFloat(60)
	r := p.Div(sixty)
	fmt.Println("Results: ", r, r.Mul(sixty))
}
```

Thanks,
-rif

**Comment by rif** [comment]
It prints Results:  0.0031666666666667 0.190000000000002

**Comment by yangwenmai** [comment]
because, r is 0.0031666666666667,so 0.0031666666666667 * 60 = 0.190000000000002.
It's correct result.

**Comment by vadimg** [comment]
What @yangwenmai said is correct. If you want lossless rational numbers, you should use Go's builtin big.Rat, but check Decimal's README for why that might not be a good idea if you're using it to represent money.
