### ISSUE TITLE
(Div)The second result is inconsistent with the first result

### ISSUE THREAD

**Issue by godemogit** [shopspring/decimal#225]
ide version: goland 2020.3.4
go version: 1.15.5
go frame: gin
decimal version: 1.2.0

```
price := decimal.NewFromFloat(0.6)
quantity := decimal.NewFromInt(100)
subtotal := price.Div(quantity)
log.Println(subtotal)
```
first print: 0.006
second print: 0.01
net print: 0.01
...

![1618164072715](https://user-images.githubusercontent.com/80087514/114315773-fec62280-9b32-11eb-8e5f-1e46117d0cdd.jpg)

**Comment by mwoss** [comment]
Hi @godemogit. I was not able to reproduce this error. Could you provide an answer to these questions? :D 
What operating system do you use? Are you using a built-in logger or some external implementation? Did you modify the `DivisionPrecision` global variable anywhere in your code? Can you provide `Exponent()` and `Coefficient()`  return values of the subtotal var?

**Comment by godemogit** [comment]
operating system: mac 11.2.3
log: logrus 1.8.1
"decimal.DivisionPrecision" is set? no
![1618193705283](https://user-images.githubusercontent.com/80087514/114332173-3c996a00-9b78-11eb-98ce-feb40f6e4cdc.jpg)
thk you for your reply

**Comment by godemogit** [comment]
My fault，I called in other places
`decimal.DivisionPrecision = 2`
But why does using “DivisionPrecision” cause this error？

**Comment by mwoss** [comment]
`DivisionPrecision` is a global variable used for rounding the output of the division. It is useful for calculations when the division result is not an exact number for example:
```go
decimal.DivisionPrecision = 2
one := decimal.RequireFromString("1.0")
three := decimal.RequireFromString("3.0")
res := one.Div(three) 
fmt.Println(res) // 0.33
```
