### ISSUE TITLE
please add get original value funcion

### ISSUE THREAD

**Issue by piyongcai** [shopspring/decimal#237]
## in current decimal，IntPart Function to get decimal IntPart value
```go
// IntPart returns the integer component of the decimal.
func (d Decimal) IntPart() int64 {
	scaledD := d.rescale(0)
	return scaledD.value.Int64()
}
```
## BUT, IN SOM TIME, NEED TO GET ORIGINAL VALUE
eg:  **PROTOBUF** , you need define Decimal message, and you need convert between proto.Decimal and decimal.Decimal

so, it's really neet to to get original value function,

To get this purpose, I copied decimal code, and Add **Int64Value** function

**PLEASE ADD**

**PLEASE ADD**

**PLEASE ADD**

```go
// Int64Value returns the original  value.
func (d Decimal) Int64Value() int64 {
	return d.value.Int64()
}
```

##  the follw code is  my proto Decimal define：
```protobuf
// Example: 12345.6789 -> { units = 12345, nanos = 678900000 }
message Decimal {

  // Whole units part of the amount
  int64 val = 1;

  // Nano units of the amount (10^-9)
  // Must be same sign as units
  int32 exp = 2;
}
```

### 1、decimal.Decimal -> proto.Decimal
```go
func FromDecimal(d decimal.Decimal) *proto.Decimal {
	return &Decimal{
		Val: d.Int64Value(),
		Exp: d.Exponent(),
	}
}
```

### 2、proto.Decimal -> decimal.Decimal
```go
func (x proto.Decimal) ToDecimal() decimal.Decimal {
	return decimal.New(x.Val, x.Exp)
}
```

**Comment by mwoss** [comment]
Hi @piyongcai! That sounds like a good idea, I will add your request to my backlog.
In the meantime, you can use the `Coefficient` method to simulate the behaviour you want. 
Example:
```golang
d := NewFromFloat(5.45)
d.Coefficient().Int64()
```

**Comment by piyongcai** [comment]
thanks

**Comment by piyongcai** [comment]
```go
// Coefficient returns the coefficient of the decimal.  It is scaled by 10^Exponent()
func (d Decimal) Coefficient() *big.Int {
	d.ensureInitialized()
	// we copy the coefficient so that mutating the result does not mutate the
	// Decimal.
	return big.NewInt(0).Set(d.value)
}
```

in Coefficient function, call big.NewInt(0).Set(d.value), this isn't a good method.

**Comment by mwoss** [comment]
@piyongcai What do you mean by "this isn't a good idea"? Could you elaborate on that?

**Comment by clstb** [comment]
Had the same problem and drafted a PR for this @ #241.

**Comment by mwoss** [comment]
@clstb Maybe I'm still asleep, but what is the difference between your proposed implementation and an example I've shoved earlier `d.Coefficient().Int64()`?

**Comment by clstb** [comment]
You were not asleep but I was apparently. I plugged you workaround into my test case and it errored. I thought this ` It is scaled by 10^Exponent()` was the culprit since the value I got mismatched exactly by that.

**Comment by mwoss** [comment]
So I guess the most suitable option here would be to extend API by adding the `CoefficientInt64` method or something similar then.
Also, I still would love to know what @piyongcai had in mind by telling "this isn't a good idea", it might be helpful tho.

**Comment by piyongcai** [comment]
```go
// Coefficient returns the coefficient of the decimal.  It is scaled by 10^Exponent()
func (d Decimal) Coefficient() *big.Int {
	d.ensureInitialized()
	// we copy the coefficient so that mutating the result does not mutate the
	// Decimal.
	return big.NewInt(0).Set(d.value)
}
```
Because this method has a very low performance。
in fact， the flow method is better way.
```go
// Int64Value returns the value.
func (d Decimal) Int64Value() int64 {
	return d.value.Int64()
}
```

In the usage scenario of protobuf, it is generally used for amount calculation, and the maximum decimal number is set to 4 bits.The message is defined as follows.
```protobuf
// Example: 12345.6789 -> { units = 12345, exp = 4} = 1.2345
message Decimal {

  // Whole units part of the amount
  int64 val = 1;

  // Nano units of the amount (10^-9)
  // Must be same sign as units
  int32 exp = 2;
}
```
I can convert between the two in the simplest way

**Comment by mwoss** [comment]
Yup, so let's expose new public method called `CoefficientInt64` that would explicitly return coef as int64 value. It should resolve your issue and probably be helpful for others. I will craft the PR later today.

**Comment by piyongcai** [comment]
thanks

**Comment by mwoss** [comment]
#244 has been merged to main branch. 
@piyongcai @clstb can you take a look if this is something you had in minds? :D

**Comment by piyongcai** [comment]
3ks
