### ISSUE TITLE
Wishlist - example with nullableFloat64 / or introduce newFromNullable 

### ISSUE THREAD

**Issue by johndpope** [shopspring/decimal#248]
Current monster code is to just defer to string - 
<img width="709" alt="Screen Shot 2021-09-23 at 2 36 48 am" src="https://user-images.githubusercontent.com/289994/134385362-560ead8b-96a0-4ec7-8c63-5f7f8aaf899e.png">

https://github.com/guregu/null
it seems without this extra library - it's a pain to work with api that returns nullabe floats.
if its null - I just want it to be 0.

**Comment by mwoss** [comment]
Hi @johndpope :3 Am I understanding it correctly, that some kind of API that you are currently using may return float or nil? Couldn't you leverage Go behaviour that every basic type have a zero value? For example ints, floats use 0 as a "zero" value. 
Only pointers can be nullable, or as you mentioned by using https://github.com/guregu/null every type can be, but we are aiming for zero dependency library and we not gonna introduce any new initializers that use types from that 3rd party lib.

**Comment by johndpope** [comment]
I think they will update library but there’s delays. I don’t want to wait. Any solution would be good. I can’t work out how to coerce it.

**Comment by mwoss** [comment]
Oh, I think I have not understood your question previously. So you would like to serialize nil values directly to zero-decimal, yes?
I would propose you to create a new init method such as:
```go
func NewFromNullableFloat(value *float64) Decimal {
	if value == nil {
		return New(0, 0)
	}
	return NewFromFloat(*value)
}
```
The implementation uses public methods, so you can do it on your own without forking the library.

**Comment by johndpope** [comment]
thanks this is helpful.
