### ISSUE TITLE
Will Coefficient() ever return a multiple of ten?

### ISSUE THREAD

**Issue by MichaelSnowden** [shopspring/decimal#262]
For a given Decimal, I can obtain the coefficient and exponent using the `.Coefficient()` and `.Exponent()` methods. I know that the value of the decimal is `coefficient * 10 ^ exponent`. From what I can tell, these are normalized so that coefficient will never be a multiple of 10. Like, for example, if the value is `100`, the coefficient will be `1` and the exponent will be 2. However, it could also be represented with coefficient as `10` and exponent as `1`, or `1000` with the exponent as `-1`.

I have built some assumptions into my code that rely on the coefficient never being a multiple of 10. I use this to basically count the number of significant digits in a number, by doing `ceil(log_10(coefficient))`. Will this always be valid, or could the coefficient be a multiple of 10?

**Comment by mwoss** [comment]
Hi @MichaelSnowden! Your assumption is usually true, but not always. It mainly depends on how decimals are initialized using this library. For example, if someone uses `New` to init decimal, no normalizations are performed, arguments are passed as they are.
```go
d := New(100, 5)
fmt.Println(d.Coefficient()) // 100
fmt.Println(d.Exponent())    // 5
```

**Comment by MichaelSnowden** [comment]
Gotcha. Thanks!
