### ISSUE TITLE
Unable MarshalJson without quotes

### ISSUE THREAD

**Issue by rtjoseph11** [shopspring/decimal#28]
I have strict json parser as a consumer of an api using the Decimal type. Is there a way to Marshal as a number rather than a string? The quotes seem to be hardcoded right now in the marshal.

**Comment by vadimg** [comment]
This is now supported, as of https://github.com/shopspring/decimal/commit/d6f52241f332c63811249bd79a522406bea1a7c9

Please note that this is dangerous, as many JSON unmarshallers do not support arbitrary-precision numbers, so you might lose precision (and potentially silently lose precision, such as in Javascript).
