### ISSUE TITLE
Empty string to decimal.Zero

### ISSUE THREAD

**Issue by shenghui0779** [shopspring/decimal#287]
```go
v, err := decimal.NewFromString("")

// err == nil
// v == decimal.Zero
```

**Comment by hunjixin** [comment]
any progress?

**Comment by dreson4** [comment]
This kind of makes sense when decoding json, some APIs are designed badly sometimes they return a number sometimes empty string, if using decimal.Decimal then it fails, one has to maybe create a custom wrapper which leads to type casting everywhere, or implement custom unmarshal function on every struct that has this problem.
