### ISSUE TITLE
trimTrailingZeros should be an option

### ISSUE THREAD

**Issue by jayd3e** [shopspring/decimal#31]
Right now it's [assumed](https://github.com/shopspring/decimal/blob/master/decimal.go#L375) that trailing zeros should be removed upon a call to `Value`, as a decimal is being serialized into the database.  This doesn't take into account cases where you want to keep the number of decimal places consistent across the board.  For example, if I created a `Decimal` via:

```
dec, _ := decimal.NewFromString("100.00")
```

I would expect it to enter the database as "100.00".  When in actuality, the trailing zeros are removed and "100" is saved.  This creates some interesting scenarios when storing and retrieving decimals from the database.  I would expect the precedent to be that decimals are represented as a string in exactly the same way they were created, unless the user does an operation that would change the precision(such as using `StringFixed`).

**Comment by ocZio** [comment]
@jayd3e what about using the StringFixed instead?

**Comment by jayd3e** [comment]
I just ran into this issue again today due to [this commit](https://github.com/shopspring/decimal/commit/4e5e2ed9487b5591a148c917ff79cc4c6fb56a14).  Yeah, I really don't think it's the job of the library to make these kinds of decisions on precision.  If I enter "100.00" into a decimal type, I expect to get "100.00" back out again.  It's deceiving to have the precision changed by the library.  This is especially true when you are putting the value into the database and retrieving it again.  You want the decimal value to be exactly the same as what you entered into the database, but under the current system, it is being changed.

**Comment by mwoss** [comment]
Hi @jayd3e. This will be fixed in the next releases. Stay tuned.

**Comment by mwoss** [comment]
Fixed in #159 (revert of #46). Closing.
