### ISSUE TITLE
the description of Copy() method does not correspond to reality

### ISSUE THREAD

**Issue by lexand** [shopspring/decimal#327]
Method Copy() says `// Copy returns a copy of decimal with the same value and exponent, but a different pointer to value.`

**Got:**
Simple test show that pointers are actually equal
```go
func TestDecimal_Copy(t *testing.T) {
	a := decimal.RequireFromString("1")
	b := a.Copy()

	refA := reflect.ValueOf(a)
	refB := reflect.ValueOf(b)

	ptrA := refA.Field(0).Pointer()
	ptrB := refB.Field(0).Pointer()

	assert.NotEqual(t, ptrA, ptrB)
}
```

Your test for Copy() method does not check inequality of pointers 
```go
func TestCopy(t *testing.T) {
	origin := New(1, 0)
	cpy := origin.Copy()

	if cpy.Cmp(origin) != 0 {
		t.Error("expecting copy and origin to be equals, but they are not")
	}

	//change value
	cpy = cpy.Add(New(1, 0))

	if cpy.Cmp(origin) == 0 {
		t.Error("expecting copy and origin to have different values, but they are equal")
	}
}
```
![copy](https://github.com/shopspring/decimal/assets/927515/b44ae942-bb84-407e-96cc-c1cc0d0bcf76)

**Expect:**
values have different pointers

```
$ go version
go version go1.20.5 linux/amd64
```

**Comment by mwoss** [comment]
Thanks for the report! Issue is fixed by https://github.com/shopspring/decimal/pull/278
