### ISSUE TITLE
Removing possible spaces creating from string.

### ISSUE THREAD

**Issue by cydside** [shopspring/decimal#349]
Could you please add a spaces remover when creating a new decimal from string?
```go
	price, err := decimal.NewFromString("        136.02  ")
	if err != nil {
		panic(err)
	}
```
this code panics! Just a simple trim() should be really appreciated in my opinion. Thanks for your work.

**Comment by mwoss** [comment]
Hi @cydside! I'll have to think about it for a while. On the one hand, it sounds like a good idea, but on the other hand, why should an incorrectly formatted input be considered correct and implicitly converted? `"        136.02  "` is not a valid decimal, and the library returns it as an error, so a user can easily recover from it. Also, if we add implicit conversion we would break backward compatibility.

**Comment by cydside** [comment]
Hi @mwoss, I got the point. Thanks.
