### ISSUE TITLE
Reading NULL value from database

### ISSUE THREAD

**Issue by ainvaltin** [shopspring/decimal#35]
Currently there is error when reading from database where source field is NULL. Please add NullDecimal type so that everyone doesn't need to roll their own.

type NullDecimal struct {
	Decimal Decimal
	Valid   bool // Valid is true if Decimal is not NULL
}

// Scan implements the Scanner interface.
func (nd *NullDecimal) Scan(value interface{}) error {
	if value == nil {
		nd.Decimal, nd.Valid = Zero, false
		return nil
	}
	nd.Valid = true
	return nd.Scan(value)
}

// Value implements the driver Valuer interface.
func (nd NullDecimal) Value() (driver.Value, error) {
	if !nd.Valid {
		return nil, nil
	}
	return nd.Decimal.String(), nil
}

**Comment by victorquinn** [comment]
This was fixed in #32 so I'm closing this issue. Decimal now has a `NullDecimal` type exactly as suggested here.
