### ISSUE TITLE
update go.mod version

### ISSUE THREAD

**Issue by mrbardia72** [shopspring/decimal#353]
go 1.7 ==>g.122

**Comment by mwoss** [comment]
Go version in `go.mod` specifies the minimum required version to compile and run the given code, in this library case it's `1.7`. So we won't update it.

**Comment by mrbardia72** [comment]
If it is updated, will there be a problem in the execution process? Or will it disturb the dependency of a certain hat

**Comment by mwoss** [comment]
No there won't be any execution problems, but most tools will expect that the given code requires >=Go1.22 to compile and run. Also, the library users would probably assume the library is using constructs and language features available in Go1.22 and later.
