### ISSUE TITLE
Preferred way to compare with 0

### ISSUE THREAD

**Issue by sunprophit** [shopspring/decimal#37]
What is preferred way to compare decimals with 0?
Does decimal.Zero can be used?

**Comment by james-maloney** [comment]
I use the `Equals` method
```Go
if d.Equals(decimal.Zero){
}
```

**Comment by victorquinn** [comment]
@sunprophit it seems @james-maloney answered this question.

@sunprophit if you have suggestion for the library, find bugs, or have new feature ideas please open another issue.
