### ISSUE TITLE
New maintainer?

### ISSUE THREAD

**Issue by sambengtson** [shopspring/decimal#43]
First off, awesome library.

I noticed that there are some new pull and feature requests recently.  I currently have the time and motivation to work on this project to try to knock some of these out.  Let me know if I can offer my services to be a maintainer of this project.

**Comment by victorquinn** [comment]
Hey @sambengtson thanks for the offer! 

As of today I'm taking over maintenance of this project and hoping to merge most of these PRs shortly. Sorry it went a bit neglected for a bit there!

**Comment by sambengtson** [comment]
@victorquinn Awesome thanks!
