### ISSUE TITLE
document required: decimal.Zero should never be compared with == or !=

### ISSUE THREAD

**Issue by h12w** [shopspring/decimal#47]
decimal.Zero should be removed unless the following code is valid:

```go
if d == decimal.Zero {
}
```

**Comment by james-maloney** [comment]
This request would break backwards compatibility.

The decimal type also has an equals method you can use in conjunction with `decimal.Zero`

```Go
if d.Equals(decimal.Zero){
}
```

**Comment by h12w** [comment]
At least a warning message should be added to decimal.Zero, like:

```
Zero constant, to make computations faster.
Warning: Zero should never be compared with == or != directly, please use decimal.Equal or decimal.Cmp instead.
```

**Comment by mwoss** [comment]
@h12w `decimal.Zero` was created to make computation faster - it's documented. Also, not only `decimal.Zero` but all decimals should be compared using build-in library method like `Equals`, `Cpm`, etc.

**Comment by mwoss** [comment]
Additional documentation provided for `decimal.Zero`
