### ISSUE TITLE
Rescaled decimal string representation does not match godoc

### ISSUE THREAD

**Issue by cmars** [shopspring/decimal#5]
The godoc comment on the behavior of `Decimal.rescale`:
```
// Rescale returns a rescaled version of the decimal. Returned
// decimal may be less precise if the given exponent is bigger
// than the initial exponent of the Decimal.                  
// NOTE: this will truncate, NOT round                        
//                                                            
// Example:                                                   
//                                                            
//  d := New(12345, -4)                                       
//  d2 := d.rescale(-1)                                       
//  d3 := d2.rescale(-4)                                      
//  println(d1)                                               
//  println(d2)                                               
//  println(d3)                                               
//                                                            
// Output:                                                    
//                                                            
//  1.2345                                                    
//  1.2                                                       
//  1.2000                                                    
//                                                            
```
indicates that the following test should pass:
```
func TestNegativeScale(t *testing.T) {
       ref := New(12345, -4)
       for _, testCase := range []struct {
               d Decimal
               s string
       }{
               {ref, "1.2345"},
               {ref.rescale(-1), "1.2"},
               {ref.rescale(-1).rescale(-4), "1.2000"},
       } {
               if testCase.d.String() != testCase.s {
                       t.Errorf("expected %q got %q", testCase.s, testCase.d.String())
               }
       }
}
```

However, `Decimal.String` does not match this behavior. The third test case fails, as the zeroes to the right are dropped; you get "1.2".

In the case of representing currency amounts as a string, I'd want `New(5, -2).String()` to give me "5.00" instead of "5"... or if `String` isn't appropriate for this, then I need a `StringXyz` method variant that retains zero placeholders for the full scale of the decimal.

**Comment by vadimg** [comment]
The StringScaled method should do what you want. Unfortunately, I just realized that it has a bug in that it doesn't round. This will be fixed tomorrow.

**Comment by vadimg** [comment]
Ah, now I see that StringScaled doesn't do what you want. You want to scale from a higher exponent to a lower one, padding the number with 0s. This is another bug that I should fix tomorrow

**Comment by vadimg** [comment]
Looks like by "tomorrow" I meant "in 3 months". Better late than never, I guess!

This has now been fixed. To prevent breaking other people's code, `StringScaled` continues to work as it did before, but now it is marked as deprecated. To get the functionality you are looking for, you should use `StringFixed`. It works similar to javascript's `toFixed` method, which means that `NewFromFloat(0).StringFixed(2)` outputs "0.00".
