### ISSUE TITLE
Floor() and Ceil() mistreat positive exponent 

### ISSUE THREAD

**Issue by tbrs** [shopspring/decimal#68]
`New(1,1).Ceil()` and `New(1,1).Floor()` return 1. Calling the same functions for `New(10,0)` gives 10 which is the expected value in both cases. Unless I missed something here, it looks like a bug.

#64 provides more details and suggests a possible solution.

**Comment by tbrs** [comment]
@victorquinn, any feedback on this would be highly appreciated. Thanks!

**Comment by victorquinn** [comment]
@tbrs sorry for the radio silence here, I thought I had already commented on it! Will respond on the PR

**Comment by tbrs** [comment]
@victorquinn, no problem!

**Comment by tbrs** [comment]
#64 landed on master, closing the issue.
