### ISSUE TITLE
Start tagging releases?

### ISSUE THREAD

**Issue by evq** [shopspring/decimal#69]
Hey all! Thanks for the really useful package.

I was wondering if you are open to starting to tag releases with semantic versions (e.g. v0.0.1). I've been refreshing my go knowledge and discovered the `go dep` tool. It uses github tags for explicit version pins, and I'd love to pin a particular version of decimal instead of the master branch. Thanks! :)

**Comment by victorquinn** [comment]
Excellent call, I’ve been meaning to do that for awhile and haven’t! I certainly will and will leave this issue open until I do tag it

**Comment by victorquinn** [comment]
Just tagged the current version as `1.0.0` and will use semver from here on out :)

**Comment by evq** [comment]
thanks @victorquinn :)

**Comment by victorquinn** [comment]
👍 sorry it took so long!
