### ISSUE TITLE
after Mul or Div, the method of Exponent returns wrong result  

### ISSUE THREAD

**Issue by plhwin** [shopspring/decimal#71]
```
package main

import (
	"fmt"
	"github.com/shopspring/decimal"
)

func main() {
	s := "13181.463"
	f1, _ := decimal.NewFromString(s)
	d := decimal.NewFromFloat(1000)
	f2 := f1.Mul(d)
	f3 := f1.Div(d)
	f4 := f1.Mul(d).Div(d)
	fmt.Println(f1, f1.Exponent(), f2, f2.Exponent(), f3, f3.Exponent(), f4, f4.Exponent())
}
```

output:
```
13181.463 -3 13181463 -3 13.181463 -16 13181.463 -16
```

f2.Exponent, f3.Exponent(), f4.Exponent() are all return a wrong result.

**Comment by tbrs** [comment]
Decimal values look correct, though. @plhwin, do I understand correctly that you expect `Exponent()` to return -3, 0, -6 and -3 respectively for f1, f2, f3 and f4?

To me `Exponent()` and `Coefficient()` look like simple accessors for private fields of a `Decimal`. The values they return only represent the internal state which is not guaranteed to be "normalized". As rescaling has its cost, it's not always performed to minimize the `value` part.

As an option, we could implement a new method for prettifying the exponent value (or, maybe, there is one which I missed?). @victorquinn, what do you think?

**Comment by stevenroose** [comment]
I'm experiencing this. I thought a "normalize" would happen before calling this methods.

However, in my case, the entire amount is wrong. It went from being 7700.25 to coefficient 3220923705161793536 and exponent -16.

**Comment by gz-c** [comment]
@stevenroose do you have sample code to reproduce that

**Comment by stevenroose** [comment]
@gz-c unfortunately not. I tried to reproduce, but it happened in a running system that had quite high throughput at the time, so I couldn't find the exact values.

I did a preemptive change that avoids as much as possible any divisions. (F.e. by using shifts when dividing by 100 and 1000.) For now I haven't encountered any problems anymore, but we don't do divisions anymore basically.

**Comment by stevenroose** [comment]
For my part, you can consider this issue closed, I will open a new one in case it would happen again and I can collect the necessary data.
