### ISSUE TITLE
RoundBank produces incorrect results depending on Decimal's internal representation

### ISSUE THREAD

**Issue by freakingawesome** [shopspring/decimal#75]
The `RoundBank()` function, given the decimal value `2.5`, should return `2`. This works as expected when your decimal is represented by `New(25, -1)`.

However, when represented by `New(250, -2)`, the function `RoundBank()` gives the incorrect result of `3`.

Here is a currently failing test which illustrates the problem:

```golang
func TestRoundBankAnomaly(t *testing.T) {
    a := New(25, -1)
    b := New(250, -2)

    if !a.Equal(b) {
        t.Errorf("Expected %s to equal %s", a, b)
    }

    expected := New(2, 0)

    aRounded := a.RoundBank(0)
    if !aRounded.Equal(expected) {
        t.Errorf("Expected bank rounding %s to equal %s, but it was %s", a, expected, aRounded)
    }

    bRounded := b.RoundBank(0)
    if !bRounded.Equal(expected) {
        t.Errorf("Expected bank rounding %s to equal %s, but it was %s", b, expected, bRounded)
    }
}
```

**Comment by freakingawesome** [comment]
I stumbled across this bug when using `RoundBank` on the result of decimal multiplication (which may increase the `exp` of `Decimal`), which leads me to believe that the incorrect results from this bug are subtle and widespread.

**Comment by orian** [comment]
@freakingawesome do you mean the bug is still there? Could you give some extra examples?

**Comment by freakingawesome** [comment]
No, the bug is now fixed. What I meant is that it was a subtle bug that has existed for years, so loads of calculations throughout the years could be slightly incorrect, especially is you were to run comparisons against the same set of input, before and after the bug was fixed.

**Comment by orian** [comment]
Thanks for clarification.

**Comment by mwoss** [comment]
@freakingawesome Thanks for explanations of this bug and fixing it :)) I'm closing the issue.
