### ISSUE TITLE
Renamings: NewFromFloatWithPrecision, NewFromFloatExact

### ISSUE THREAD

**Issue by igrmk** [shopspring/decimal#79]
This is arguably of course. In my opinion NewFromFloatWithPrecision(value float64, prec int32) is much more friendly name than NewFromFloatWithExponent(value float64, exp int32). Probably not all people working with decimal numbers know what is exponent. Argument prec should be treated as -exp in this case and current method should be deprecated. 

Frankly speaking I would go further and deprecate NewFromFloat in favor of NewFromFloatExact. This should make people think about memory needed to store float without specifying precision.

**Comment by igor-mikushkin** [comment]
BTW. Current implementation of NewFromFloat doesn't store float64 exact actually. But I made this PR that fix it https://github.com/shopspring/decimal/pull/78

**Comment by igor-mikushkin** [comment]
Please inform if you can accept such a PR. I would be happy to do it.
