### ISSUE TITLE
NewFromString doesn't read  scientific notation

### ISSUE THREAD

**Issue by abourget** [shopspring/decimal#8]
`decimal.NewFromString("512e-3")` errors out. Is that not a valid number ?

**Comment by vadimg** [comment]
You're right, I've didn't add the ability to parse scientific notation. It's not a top priority for us, so I probably won't have time to add it anytime soon. If you end up implementing it yourself, please send me a pull request!

**Comment by thiagoarruda** [comment]
Hi! I'm new to Go, so I apologize if it's a silly suggestion, but maybe this would work well enough?

In method `NewFromString`, inside `if len(parts) == 1`:
```go
if strings.Contains(value, "e") {
  fValue, err := strconv.ParseFloat(value, 64)
  if err != nil {
    return Decimal{}, fmt.Errorf("can't convert %s to decimal", value)
  }
  return NewFromFloat(fValue), nil
}
```

**Comment by abourget** [comment]
@thiagoarruda I think that would limit the number of decimals and the precision.. that's the goal of that whole library.. it's to handle any number (at least, a large number) of digits and decimals..

**Comment by thiagoarruda** [comment]
@abourget Ah, good point! Didn't think of that, the numbers I'm working with aren't very large. Thanks for the reply!

**Comment by thiagoarruda** [comment]
I decided to have another go (ha!) at it. Here's the gist: https://gist.github.com/thiagoarruda/f4f9445aeb0a3f0a8eb1

Seems to work pretty well even for pretty large numbers/exponents. Let me know what you think!

**Comment by vadimg** [comment]
Thank you for this code, it seems reasonable. I do want to make a few comments, but it's hard for me to do so in a gist. Can you submit a pull request (with tests) please?

**Comment by vadimg** [comment]
This feature has now been landed, thank you for the pull request!
