### ISSUE TITLE
Performance issue preventing production use

### ISSUE THREAD

**Issue by technicalviking** [shopspring/decimal#81]
I'm currently working on an application that would benefit greatly from this lib, due to requirements with floating point precision.  However benchmark tests of that application are worrying.

The scenario involves creating Decimal values, and then calling the various comparison methods on them.   This sequence of events happens millions of times.   Immediately after converting my code to use Decimal (instead of big.float, which was showing unacceptable precision loss after 20 significant digits), the performance time of our benchmark test went from 3-4 minutes for the test, to 22, on the same processor.  pprof helped narrow the problem to the fact that your implementation of CMP involves the creation of an additional 2 decimal objects whenever the 'exp' values were different (which was pretty much every time), which is in line with the fact that after the change, 60% of the cpu time was spent allocating memory.

Is there a particular reason this approach was taken?   Would a PR attempting to optimize this be accepted?

**Comment by victorquinn** [comment]
Yes, would gladly accept a PR to optimize it!

Not sure as to why things were written that way to begin with (I inherited this project) but obviously a faster way to accomplish the same thing that doesn't break existing functionality would be amazing.

**Comment by robaho** [comment]
There are similar problems with the Add, and other computation methods... There is no reason to rescale the decimal if both operands already have the same scale - that is the core problem with the implementation.

**Comment by robaho** [comment]
@technicalviking you might be interested in this [fixed](https://github.com/robaho/fixed)

**Comment by kempeng** [comment]
Any progress on this issue?

**Comment by k1ng440** [comment]
hi, any progress?

**Comment by robaho** [comment]
Not sure why the owner told them that a PR would be accepted, they submitted it, and it has languished. I think your best best is to fork and apply the PR.

**Comment by technicalviking** [comment]
@robaho I really wish I'd come back to this thread the first time you commented on it!  Unfortunately, life was in the way (had a kid) and wasn't able to resume the project.  Rather than submitting the PR myself, I'd gone ahead and tried to integrate a static C lib (yay for CGO) that handled decimal operations, with mixed results.  Now that I have time to come back to this project, I'll be trying to use the code you linked to above.  @k1ng440 I recommend you do the same.

**Comment by robaho** [comment]
Congrats! Just remember if using my ‘fixed’ it is fixed precision, not infinite precision. The decimal package is infinite.

**Comment by victorquinn** [comment]
Hi all, sorry this is languishing — to explain a bit, I left Spring (the company that started this project) and they removed me from the repo :( 

So I’m unable to accept this change or any other PR. 

Kind of agree, if no one accepts this, fork it and move on 😢

**Comment by technicalviking** [comment]
> 
> Congrats! Just remember if using my ‘fixed’ it is fixed precision, not infinite precision. The decimal package is infinite.
@robaho 
Finite precision is fine with me.  That actually makes things easier for me, tbh.

**Comment by mwoss** [comment]
Thanks all for this discussion and @technicalviking for addressing this issue. 
I'm a new maintainer and it took me some time to finally "dug" into this issue. 
I've added this issue to the backlog and we will try to fix this performance issue in 1.2.0 release (@technicalviking, @robaho, @k1ng440, @kempeng).

**Comment by mwoss** [comment]
Closed by #160. 
I still think there is room for optimizing operation on decimals with different exp attributes, we will add corresponding task to backlog fro this.
