### ISSUE TITLE
Error decoding string '""': can't convert "" to decimal

### ISSUE THREAD

**Issue by t0dbld** [shopspring/decimal#83]
as title indicates issue is when used in struct and a retrieved value is an empty string, omitempty is no help.  This makes using the library hard as when pulling in data from outside sources you don't know when they could could suddenly do this, and this error is than breaking because no data will be unmarshaled 

` type example struct {
Value decimal.Decimal json:"value, omitempty" } `

relevant code in library : 
```
 // UnmarshalJSON implements the json.Unmarshaler interface.
func (d *Decimal) UnmarshalJSON(decimalBytes []byte) error {
	if string(decimalBytes) == "null" {
		return nil
	}

	str, err := unquoteIfQuoted(decimalBytes)
	if err != nil {
		return fmt.Errorf("Error decoding string '%s': %s", decimalBytes, err)
	}

	decimal, err := NewFromString(str)
	*d = decimal
	if err != nil {
		return fmt.Errorf("Error decoding string '%s': %s", str, err)
	}
	return nil 
```

and : 

```
func NewFromString(value string) (Decimal, error) {
	originalInput := value
	var intString string
	var exp int64

	// Check if number is using scientific notation
	eIndex := strings.IndexAny(value, "Ee")
	if eIndex != -1 {
		expInt, err := strconv.ParseInt(value[eIndex+1:], 10, 32)
		if err != nil {
			if e, ok := err.(*strconv.NumError); ok && e.Err == strconv.ErrRange {
				return Decimal{}, fmt.Errorf("can't convert %s to decimal: fractional part too long", value)
			}
			return Decimal{}, fmt.Errorf("can't convert %s to decimal: exponent is not numeric", value)
		}
		value = value[:eIndex]
		exp = expInt
	}

	parts := strings.Split(value, ".")
	if len(parts) == 1 {
		// There is no decimal point, we can just parse the original string as
		// an int
		intString = value
	} else if len(parts) == 2 {
		// strip the insignificant digits for more accurate comparisons.
		decimalPart := strings.TrimRight(parts[1], "0")
		intString = parts[0] + decimalPart
		expInt := -len(decimalPart)
		exp += int64(expInt)
	} else {
		return Decimal{}, fmt.Errorf("can't convert %s to decimal: too many .s", value)
	}

	dValue := new(big.Int)
	_, ok := dValue.SetString(intString, 10)
	if !ok {
		return Decimal{}, fmt.Errorf("can't convert %s to decimal", value)
	}

	if exp < math.MinInt32 || exp > math.MaxInt32 {
		// NOTE(vadim): I doubt a string could realistically be this long
		return Decimal{}, fmt.Errorf("can't convert %s to decimal: fractional part too long", originalInput)
	}

	return Decimal{
		value: dValue,
		exp:   int32(exp),
	}, nil
}

```
there is a check for scientific notation, and a check if there is a decimal, but none for an empty string, 
there seems to be 2 ways to fix this, either conform if possible to the omitempty with golang json, if this is not possible than add a check for empty values and return 0 value int, similar to the "is no decimal point we can just parse the original string as an int" 

looking at closed issues and the code further I see [fix](https://github.com/shopspring/decimal/commit/b9ab2bce742bffa417d3c01158f6062d5e05ecb4) for null, possibly just add "" as well  eg : 

```
func (d *Decimal) UnmarshalJSON(decimalBytes []byte) error {
-	if string(decimalBytes) == "null" {
+	if string(decimalBytes) == "null" || string(decimalBytes) == "" {
 		return nil
 	}
```

**Comment by victorquinn** [comment]
I'm sorry to say that this is the expected behavior. 

Take a look at [this issue](https://github.com/golang/go/issues/22182) which describes how the in-built json unmarshal works in Go and specifically how it deals with unmarshaling an empty string into an int.

The tl;dr is well enumerated by @rsc at the bottom of the issue:

> Since the empty string is not the string form of any integer and the code has worked this way since 2012, we're not going to change this.

The same applies here. Unmarshaling an empty string to a Decimal I think should not return 0, but instead _should_ throw the error as it does today. 

So apologies, I don't think this makes sense to change as you've suggested.

**Comment by liepumartins** [comment]
Sorry to necro bump. I was writing an issue and came across this.
But what about the NullDecimal type? Would not it be ok for NullDecimal to parse empty string value?

My use case - incoming XML has attributes, that are always present, regardless of actual value e.g. `<item price="100.00" otherPrice="" />`
Currently I have to use float64 for those.

**Comment by weaming** [comment]
You can override the `UnmarshalJSON` method, and you can call the origin methods on `DecimalSafe`:

```
type DecimalSafe struct {
	dec.Decimal
}

func (d *DecimalSafe) UnmarshalJSON(decimalBytes []byte) error {
	if string(decimalBytes) == `""` {
		return nil
	}

	return d.Decimal.UnmarshalJSON(decimalBytes)
}

type YourJson struct {
	N DecimalSafe `json:"N,omitempty"`
}

func main() {
	var a YourJson
	err := json.Unmarshal([]byte(`{"N": ""}`), &a)
	if err != nil {
		panic(err)
	}
	log.Println(a.N, a.N.IsZero())
}

```
