### ISSUE TITLE
NewFromFloat loses accuracy / behavior change

### ISSUE THREAD

**Issue by jackc** [shopspring/decimal#84]
This used to pass.

```
func TestNumericFromFloat(t *testing.T) {
	fromString, err := decimal.NewFromString("12345.678901")
	if err != nil {
		t.Fatal(err)
	}

	fromFloat := decimal.NewFromFloat(12345.678901)

	if !fromString.Equal(fromFloat) {
		t.Fatalf("expected fromString (%v) to equal fromFloat (%v) but it doesn't", fromString, fromFloat)
	}
}
```

But is doesn't pass as of 78e9b82.

```
--- FAIL: TestNumericFromFloat (0.00s)
	decimal_test.go:157: expected fromString (12345.678901) to equal fromFloat (12345.6789009999993140809237957000732421875) but it doesn't
```

**Comment by Petrzlen** [comment]
+1

**Comment by igor-mikushkin** [comment]
This is correct behavior. It lost precision in previous version.
Look, here I print all the nonzero digits of the number from your test.
https://play.golang.org/p/rSyqOkSw8_X
That is how number is actually stored in Float64.

**Comment by im-kulikov** [comment]
this is not patch fix.. pls just read [semver specification](https://semver.org)

**Comment by jackc** [comment]
The underlying situation was github.com/jackc/pgx suddenly started failing on CI. Since it is a library, there is no good way to lock to a specific version of decimal and it always runs against master.

Since the new behavior is correct I have updated my integration tests to expect it.

Thanks.
