### ISSUE TITLE
RoundCash interval Is 15

### ISSUE THREAD

**Issue by candy4dmu** [shopspring/decimal#89]
`fmt.Println(decimal.NewFromFloat(3.5).RoundCash(15))`

the result Is 2.4

`fmt.Println(decimal.NewFromFloat(3.45).RoundCash(15))`

the result is 3.5 , not same with the doc.

**Comment by mwoss** [comment]
@candy4dmu Thanks for pointing this issue. You are correct, something is not working correctly. We will try to fix it as soon as possible.
