### ISSUE TITLE
Got wrong result Round()

### ISSUE THREAD

**Issue by yusank** [shopspring/decimal#97]
``` go
func Decimal() {
    f, exit := decimal.NewFromFloat(1.275).Round(2).Float64()
	if exit {
		fmt.Println("yes")
	}

	fmt.Println(f)
        // result should be 1.28, but got 1.27
}
```

I'm still new to Go, so why I got what I don't want, can anybody explain ,thx.

Is there any way to fix this?

**Comment by klauspost** [comment]
Should be fixed by #100

**Comment by leighmcculloch** [comment]
This does appear to be fixed in the latest commit. e.g. https://play.golang.org/p/3y7fw2KjHjk

**Comment by mwoss** [comment]
Apparently it was fixed. Closing the issue.
