### ISSUE TITLE
Thousands separator

### ISSUE THREAD

**Issue by NathanZarro** [shopspring/decimal#98]
I don't see a format option for thousands separators, such as commas. Am I missing it?

**Comment by peterstace** [comment]
No, you're not missing it, there is no such format option.

That would be useful for me as well (in my use case, displaying large numbers to users in a friendly way).

**Comment by mwoss** [comment]
Thanks for pointing this @NathanZarro @peterstace. Let's move the conversation to #145. I'll close this issue.
