### ISSUE TITLE
The result is wrong NewFromFloat(9784.815).StringFixedBank(2) // output: "9784.82"

### ISSUE THREAD

**Issue by famiou** [shopspring/decimal#99]
NewFromFloat(9784.815).StringFixedBank(2) // output: "9784.82"
The result is wrong ，should be output: "9784.81"

**Comment by peterstace** [comment]
9784.82 seems correct to me.

Bankers rounding (also called round-to-even) rounds such that the last digit in the result is even if the input is equidistant from two potential results.

**Comment by famiou** [comment]
It should be to discard the following decimal instead of rounding off

**Comment by peterstace** [comment]
If you want to discard digits after a certain point, you may wish to use the [Truncate](https://godoc.org/github.com/shopspring/decimal#Decimal.Truncate) function.

**Comment by famiou** [comment]
ok  thank you

**Comment by mwoss** [comment]
@peterstace Thanks for helping others :))
